WebApplication3/Components/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Data;
using WebApplication3.Models.ModuleModels;

namespace WebApplication3.ViewComponents
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext db;

        public SideBarViewComponent(ApplicationDbContext context)
        {
            db = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await GetModules();
            return View(items);
        }

        private Task<List<Module>> GetModules()
        {
            return db.Modules.ToListAsync();
        }
    }
}

WebApplication3/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    @*@@Scripts.Render("~/bundles/jquery") add to minimized javascript sheet to save on bandwith when loading pages*@
    <script src="~/bundles/jquery.js" type="text/javascript"></script>
    <script src="//cdn.ckeditor.com/4.5.8/standard/ckeditor.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.4/adapters/jquery.js"></script>
</head>
@if (SignInManager.IsSignedIn(User))
{
    <body>
        <div class="container">
            <div class="row">
                <div id="header">
                    <div id="title">
                        <h1>@Html.Partial("Components/Header")</h1>
                    </div>
                </div>
            </div>
            <div class="row" id="headerbar">

                @Html.Partial("Components/Navbar")

            </div>
            <div id="row">
                @await Component.InvokeAsync("SideBar")
               

                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
            <div id="row">
                @Html.Partial("Components/Footer")
            </div>
        </div>

        @RenderSection("Scripts", required: false)
    </body>
}
else
{
    <body>
        <div class="container">
            <div class="row">
                <div id="header">
                    <div id="title">
                        <h1>@Html.Partial("Components/Header")</h1>
                    </div>
                </div>
            </div>
            <div class="row" id="headerbar">

                @Html.Partial("Components/Navbar")
            </div>
            <div id="row">

                @*@Html.Partial("Components/Sidebar")*@


                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
            <div id="row">
                @Html.Partial("Components/Footer")
            </div>
        </div>

        @RenderSection("Scripts", required: false)
    </body>
}
</html>